Document: python2.6-coev
Title: Debian python2.6-coev Manual
Author: <insert document author here>
Abstract: This manual describes what python2.6-coev is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python2.6-coev/python2.6-coev.sgml.gz

Format: postscript
Files: /usr/share/doc/python2.6-coev/python2.6-coev.ps.gz

Format: text
Files: /usr/share/doc/python2.6-coev/python2.6-coev.text.gz

Format: HTML
Index: /usr/share/doc/python2.6-coev/html/index.html
Files: /usr/share/doc/python2.6-coev/html/*.html

  
